### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by lmly9193** [YilanBoy/simple-blog#1]
文章不錯，要不要加個 RSS 呀？不然沒法知道你有文章更新喔～

**Comment by yilanboy** [comment]
感謝 Feedback 😃，我這週會嘗試加入 RSS 訂閱的功能

**Comment by yilanboy** [comment]
已在 2953b2116a23cdf5f3ff7b90f3d999e28c14f904 中加入 Web Feed 的訂閱功能。 😃
